name: Client CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.14.0"

      - name: ðŸ”¨ Create .env file
        env:
          PROD_ENV: ${{ secrets.CLIENT_ENV }}
        run: echo "$PROD_ENV" > .env

      - name: Install dependencies & build
        run: |
          npm i -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          overwrite: true
          source: .next/standalone,.next/static,public,.env,pm2.config.js
          target: "/home/sarangsho/htdocs/sarangsho.com"

      - name: Install deps & reload on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            cd /home/sarangsho/htdocs/sarangsho.com
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            export PATH="$PATH:$HOME/.nvm/versions/node/v22.14.0/bin"
            npm i -g pm2
            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/
            pm2 delete "Sarangsho" || true
            pm2 start pm2.config.js
            pm2 save

            crontab -l 2>/dev/null | grep -q pm2 || \
            (crontab -l 2>/dev/null; echo '@reboot export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; pm2 resurrect') | crontab -
