name: Transcriptor-admin  CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.14.0"
      - name: ðŸ”¨ Create .env file
        env:
          PROD_ENV: ${{ secrets.CLIENT_ENV }}
        run: |
          echo "$PROD_ENV" > .env.local
      # Step 3: Install dependencies for both frontend and backend
      - name: Install dependencies
        run: |
          npm i  -g npm 
          npm i 
          npm run build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          overwrite: true
          source: .env.local,app,.next,public,.gitignore,components,context,hooks,lib,styles,components.json,eslint.config.mjs,next.config.ts,package.json,pnpm-lock.yaml,pm2.config.js,.env,postcss.config.mjs,tailwind.config.ts,tsconfig.json,README.md, prisma/**
          target: "/home/servicesbd/htdocs/servicesbd.top"

      - name: Build & reload on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/servicesbd/htdocs/servicesbd.top
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            export PATH="$PATH:$HOME/.nvm/versions/node/v22.14.0/bin"
            pnpm i --frozen-lockfile
            pnpm build
            pm2 start pm2.config.js || pm2 reload pm2.config.js
